spring.application.name=FTA-24-API-Gateway
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/
server.port= 8086


#Automatic routing
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
#spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


#Manual routing
#http://localhost:8086/blinkit/orders/all ==> http://localhost:8086/FTA-21-OrderMS/orders/all
spring.cloud.gateway.server.webflux.routes[0].id=orderMS
spring.cloud.gateway.server.webflux.routes[0].uri=lb://FTA-21-OrderMS
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/blinkit/**
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/foram/product/**


# filter 1 :: StripPrefix = 1 : pre-filter
#spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
#filter 2 : RewritePath : : pre-filter
# v1 = all
# /foram/product/all ==>/orders/all
# http://localhost:8086/foram/product/all ==>http://localhost:8086/FTA-21-OrderMS/orders/all
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/foram/product/(?<v1>.*),/orders/${v1}