spring.application.name=FTA_23_Eureka_Server

server.port = 8090

#Eureka will not register itselt, if false
eureka.client.register-with-eureka=false 

#Eureka will fetch its own registry, if false
eureka.client.fetch-registry=false
